title: Jack Coster - SNHU CS 499 Capstone ePortfolio
description: My  CS 499 ePortfolio hosting my three code artifacts with their original and ehanced files.
theme: just-the-docs

url: https://jcoster-snhu.github.io/SNHU-Jack-Coster-ePortfolio/index.html

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
